from src.config.default import _CN as cfg

cfg.OUTPUT = 'carla_fullimg_uavrelay_soft_planar_finetune_pe_infer'

cfg.OETR.LEGACY_CHECKPOINT = None
cfg.OETR.NORM_INPUT = True
cfg.OETR.BACKBONE.NUM_LAYERS = 50

cfg.OETR.ENHANCED.SEMANTIC_ENABLE = True
cfg.OETR.ENHANCED.SEMANTIC_SOURCE = 'dinov2'
cfg.OETR.ENHANCED.DINOV2_MODEL = 'dinov2_vitb14'
cfg.OETR.ENHANCED.SCALE_PE = True
cfg.OETR.ENHANCED.SEM_LOSS_WEIGHT = 0.1
cfg.OETR.ENHANCED.SEM_LOSS_MODE = 'mask_align'
cfg.OETR.ENHANCED.SEM_BG_WEIGHT = 0.25
cfg.OETR.ENHANCED.SEM_BG_MARGIN = 0.05
cfg.OETR.ENHANCED.SCALE_LOSS_WEIGHT = 0.0

cfg.DATASET.TRAIN.IMAGE_SIZE = [1280, 720]
cfg.DATASET.VAL.IMAGE_SIZE = [1280, 720]
